version: "3.9"
services:
  ffc-experiments:
    build:
      context: ../FeatureFlagsCo.Experiments
      args: 
        exptenv: prod
      dockerfile: Dockerfile
    image: ffc-experiments
    ports: 
      - 80:80
