version: "3.9"
services:
  # web:
  #   build: .
  #   ports:
  #     - "5000:5000"
  # redis:
  #   image: "redis:alpine"
  ffc-experiments:
    build:
      context: ../FeatureFlagsCo.Experiments
      dockerfile: Dockerfile
    image: ffc-experiments